version: "3.9"
services:

  index:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    expose:
      - "9200"
    ports:
      - "127.0.0.1:9200:9200"
    container_name: index
    environment:
      - node.name=index
      - cluster.name=opensanctions-index
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - index-data:/usr/share/elasticsearch/data
    deploy:
      placement:
        max_replicas_per_node: 1
      restart_policy:
        condition: on-failure

  app:
    image: ghcr.io/opensanctions/yente:latest
    depends_on:
      - index
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      YENTE_ELASTICSEARCH_URL: http://index:9200
      YENTE_STATEMENT_API: 'false'
      # Set this to a randomly generated string to enable the /updatez API:
      YENTE_UPDATE_TOKEN: ''
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/healthz" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s

volumes:
  index-data: null
