# This is the config file used to drive api.opensanctions.org
schedule: null
external:
  url: "https://data.opensanctions.org/datasets/latest/index.json"
  scope: all
datasets:
  - name: external_offshoreleaks
    title: ICIJ OffshoreLeaks
    url: https://data.opensanctions.org/contrib/icij-offshoreleaks/full-oldb.json
    version: "20220526"
  - name: external_gleif
    title: GLEIF Concatenated Data File
    url: https://data.opensanctions.org/contrib/gleif/gleif.json
    version: "20220527"
